import type { Media, SavedMedia } from './types';

export const mockSavedItems: SavedMedia[] = [
  {
    id: '7',
    tmdbId: '238',
    title: 'The Godfather',
    year: '1972',
    posterUrl: 'https://picsum.photos/seed/7/500/750',
    posterImageHint: 'mafia movie',
    type: 'movie',
    rating: 9.2,
    synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    genres: ['Crime', 'Drama'],
    status: 'watched',
    userRating: 10,
    notes: 'A true masterpiece of cinema. The acting and directing are flawless.',
  },
  {
    id: '8',
    tmdbId: '1399',
    title: 'Game of Thrones',
    year: '2011-2019',
    posterUrl: 'https://picsum.photos/seed/8/500/750',
    posterImageHint: 'fantasy series',
    type: 'series',
    rating: 9.2,
    synopsis: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    genres: ['Action', 'Adventure', 'Drama'],
    status: 'pending',
    userRating: null,
    notes: 'Need to start watching this soon!',
  },
  {
    id: '9',
    tmdbId: '496243',
    title: 'Parasite',
    year: '2019',
    posterUrl: 'https://picsum.photos/seed/9/500/750',
    posterImageHint: 'thriller movie',
    type: 'movie',
    rating: 8.6,
    synopsis: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    genres: ['Comedy', 'Drama', 'Thriller'],
    status: 'watched',
    userRating: 9,
    notes: 'Incredible film with a powerful message. The ending was shocking.',
  },
];
