import type { Media, SavedMedia } from './types';

export const mockSearchResults: Media[] = [
  {
    id: '1',
    tmdbId: '27205',
    title: 'Inception',
    year: '2010',
    posterUrl: 'https://picsum.photos/seed/1/500/750',
    posterImageHint: 'sci-fi movie',
    type: 'movie',
    rating: 8.8,
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    genres: ['Action', 'Sci-Fi', 'Thriller'],
  },
  {
    id: '2',
    tmdbId: '603',
    title: 'The Matrix',
    year: '1999',
    posterUrl: 'https://picsum.photos/seed/2/500/750',
    posterImageHint: 'action movie',
    type: 'movie',
    rating: 8.7,
    synopsis: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genres: ['Action', 'Sci-Fi'],
  },
  {
    id: '3',
    tmdbId: '157336',
    title: 'Interstellar',
    year: '2014',
    posterUrl: 'https://picsum.photos/seed/3/500/750',
    posterImageHint: 'space movie',
    type: 'movie',
    rating: 8.6,
    synopsis: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
  },
  {
    id: '4',
    tmdbId: '1396',
    title: 'Breaking Bad',
    year: '2008-2013',
    posterUrl: 'https://picsum.photos/seed/4/500/750',
    posterImageHint: 'drama series',
    type: 'series',
    rating: 9.5,
    synopsis: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    genres: ['Crime', 'Drama', 'Thriller'],
  },
  {
    id: '5',
    tmdbId: '66732',
    title: 'Stranger Things',
    year: '2016-',
    posterUrl: 'https://picsum.photos/seed/5/500/750',
    posterImageHint: 'horror series',
    type: 'series',
    rating: 8.7,
    synopsis: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    genres: ['Drama', 'Fantasy', 'Horror'],
  },
  {
    id: '6',
    tmdbId: '680',
    title: 'Pulp Fiction',
    year: '1994',
    posterUrl: 'https://picsum.photos/seed/6/500/750',
    posterImageHint: 'crime movie',
    type: 'movie',
    rating: 8.9,
    synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    genres: ['Crime', 'Drama'],
  },
];

export const mockSavedItems: SavedMedia[] = [
  {
    id: '7',
    tmdbId: '238',
    title: 'The Godfather',
    year: '1972',
    posterUrl: 'https://picsum.photos/seed/7/500/750',
    posterImageHint: 'mafia movie',
    type: 'movie',
    rating: 9.2,
    synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    genres: ['Crime', 'Drama'],
    status: 'watched',
    userRating: 10,
    notes: 'A true masterpiece of cinema. The acting and directing are flawless.',
  },
  {
    id: '8',
    tmdbId: '1399',
    title: 'Game of Thrones',
    year: '2011-2019',
    posterUrl: 'https://picsum.photos/seed/8/500/750',
    posterImageHint: 'fantasy series',
    type: 'series',
    rating: 9.2,
    synopsis: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    genres: ['Action', 'Adventure', 'Drama'],
    status: 'pending',
    userRating: null,
    notes: 'Need to start watching this soon!',
  },
  {
    id: '9',
    tmdbId: '496243',
    title: 'Parasite',
    year: '2019',
    posterUrl: 'https://picsum.photos/seed/9/500/750',
    posterImageHint: 'thriller movie',
    type: 'movie',
    rating: 8.6,
    synopsis: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    genres: ['Comedy', 'Drama', 'Thriller'],
    status: 'watched',
    userRating: 9,
    notes: 'Incredible film with a powerful message. The ending was shocking.',
  },
];

export const allMockMedia = [...mockSearchResults, ...mockSavedItems];
