import type { SavedMedia } from './types';

export const mockSavedItems: SavedMedia[] = [
  {
    id: '7',
    tmdbId: '238',
    title: 'O Poderoso Chefão',
    year: '1972',
    posterUrl: 'https://picsum.photos/seed/7/500/750',
    posterImageHint: 'mafia movie',
    type: 'movie',
    rating: 9.2,
    synopsis: 'O patriarca de uma dinastia do crime organizado transfere o controle de seu império clandestino para seu filho relutante.',
    genres: ['Crime', 'Drama'],
    status: 'watched',
    userRating: 10,
    notes: 'Uma verdadeira obra-prima do cinema. A atuação e a direção são impecáveis.',
  },
  {
    id: '8',
    tmdbId: '1399',
    title: 'Game of Thrones',
    year: '2011-2019',
    posterUrl: 'https://picsum.photos/seed/8/500/750',
    posterImageHint: 'fantasy series',
    type: 'tv',
    rating: 9.2,
    synopsis: 'Nove famílias nobres lutam pelo controle das terras de Westeros, enquanto um antigo inimigo retorna depois de estar adormecido por milênios.',
    genres: ['Ação', 'Aventura', 'Drama'],
    status: 'pending',
    userRating: null,
    notes: 'Preciso começar a assistir isso em breve!',
  },
  {
    id: '9',
    tmdbId: '496243',
    title: 'Parasita',
    year: '2019',
    posterUrl: 'https://picsum.photos/seed/9/500/750',
    posterImageHint: 'thriller movie',
    type: 'movie',
    rating: 8.6,
    synopsis: 'A ganância e a discriminação de classe ameaçam a recém-formada relação simbiótica entre a rica família Park e o clã indigente Kim.',
    genres: ['Comédia', 'Drama', 'Suspense'],
    status: 'watched',
    userRating: 9,
    notes: 'Filme incrível com uma mensagem poderosa. O final foi chocante.',
  },
];
